# Generated by Django 2.2.12 on 2020-06-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('company', models.CharField(max_length=100, verbose_name='公司单位及职位')),
                ('work_content', models.CharField(max_length=100, verbose_name='work_content')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('school', models.CharField(max_length=100, verbose_name='school')),
                ('professional', models.CharField(max_length=100, verbose_name='professional')),
            ],
        ),
    ]
