# Generated by Django 2.2.12 on 2020-07-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_experience_graduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
