# Generated by Django 2.2.12 on 2020-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_albumpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpic',
            name='url',
            field=models.CharField(max_length=200, verbose_name='picss'),
        ),
    ]
